name: Test MariaDB UDF

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mariadb:
        image: mariadb:10.5
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: example

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        run: docker build -t mariadb-udf-test .

      - name: Run MariaDB UDF Test
        run: |
          docker rm -f mariadb-test || true
          docker run -d --name mariadb-test -e MYSQL_ROOT_PASSWORD=example mariadb-udf-test
          sleep 60
          docker logs mariadb-test
          docker exec mariadb-test mysql -uroot -pexample -e "SELECT string_udf('Hello, World!');"
